name: 'Docker Build and Push'
description: 'Build and push Docker images using Buildx'
inputs:
  registry:
    description: 'Container registry URL'
    required: true
  username:
    description: 'Container registry username'
    required: true
  password:
    description: 'Container registry password'
    required: true
  dockerfile-path:
    description: 'Path to the Dockerfile'
    required: true
  context-path:
    description: 'Build context path'
    required: true
  build-args:
    description: 'Build arguments'
    required: true
  image-tags:
    description: 'Comma-separated list of image tags'
    required: true
  no-cache:
    description: 'Do not use cache when building the image'
    default: 'true'
    required: false
  push-image:
    description: 'Push the image after building'
    default: 'true'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Context for Buildx
      shell: bash
      run: docker context create builder

    # GitHub Action to set up Docker Buildx.
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
        endpoint: builder # address for docker socket or context from 'docker context ls'

    # GitHub Action to login against a Container registry
    # https://github.com/docker/login-action          
    - name: Login to nexus.cainc.com
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    # GitHub Action to build and push Docker images with Buildx
    # https://github.com/docker/build-push-action
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: ${{ inputs.dockerfile-path }}
        context: ${{ inputs.context-path }}
        build-args: |
          ${{ inputs.build-args }}
        tags: ${{ inputs.image-tags }}
        no-cache: ${{ inputs.no-cache }}
        push: ${{ inputs.push-image }}
